const fs = require('fs');
const path = require('path');

// Resolve SITE_URL in priority order: ENV -> package.json "homepage" -> default
function getSiteUrl() {
  if (process.env.SITE_URL) return process.env.SITE_URL.replace(/\/+$/, '');
  try {
    const pkg = require(path.resolve(__dirname, '../package.json'));
    if (pkg.homepage) return pkg.homepage.replace(/\/+$/, '');
  } catch (_) { }
  return 'https://www.example.com';
}

const SITE_URL = getSiteUrl();
// Load public routes from routes.json (single source of truth)
const routes = require(path.resolve(__dirname, '../routes.json'));

function xmlEscape(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function buildSitemapXml(urlset) {
  // Ensure non-root paths end with a trailing slash to match GitHub Pages canonical URLs
  function withCanonicalSlash(p) {
    if (!p || p === '/') return '/';
    return p.endsWith('/') ? p : `${p}/`;
  }

  const urlsXml = urlset
    .map((u) => {
      const canonicalPath = withCanonicalSlash(u.path);
      const loc = canonicalPath === '/' ? SITE_URL : `${SITE_URL}${canonicalPath}`;
      return `
  <url>
    <loc>${xmlEscape(loc || SITE_URL)}</loc>
    <lastmod>${new Date().toISOString()}</lastmod>
    <changefreq>${u.changefreq || 'weekly'}</changefreq>
    <priority>${typeof u.priority === 'number' ? u.priority.toFixed(1) : '0.5'}</priority>
  </url>`;
    })
    .join('');

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.js -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urlsXml}
</urlset>
`;
}

function copyIndexForSPA() {
  const distDir = path.resolve(__dirname, '../dist');
  const indexPath = path.join(distDir, 'index.html');

  // Only run this if dist/index.html exists (i.e., after build)
  if (!fs.existsSync(indexPath)) {
    console.log('⏭️  Skipping SPA route copy (dist/index.html not found - run after build)');
    return;
  }

  const indexContent = fs.readFileSync(indexPath, 'utf8');

  // Create a directory for each route (except '/') and copy index.html into it
  routes
    .filter(route => route.path !== '/')
    .forEach(route => {
      const routePath = route.path.slice(1); // Remove leading slash
      const routeDir = path.join(distDir, routePath);

      // Create directory if it doesn't exist
      if (!fs.existsSync(routeDir)) {
        fs.mkdirSync(routeDir, { recursive: true });
      }

      // Copy index.html to route/index.html
      const targetPath = path.join(routeDir, 'index.html');
      fs.writeFileSync(targetPath, indexContent);
      console.log(`  ✓ Created ${routePath}/index.html`);
    });

  console.log('\n✅ SPA route files created successfully!');
  console.log('   Crawlers can now access all routes directly on GitHub Pages.\n');
}

function main() {
  // Generate sitemap XML
  const xml = buildSitemapXml(routes);
  console.log(`Base URL: ${SITE_URL}`);

  // Write to public directory (for development reference)
  const publicDir = path.resolve(__dirname, '../public');
  if (!fs.existsSync(publicDir)) {
    fs.mkdirSync(publicDir, { recursive: true });
  }
  const publicPath = path.join(publicDir, 'sitemap.xml');
  fs.writeFileSync(publicPath, xml, 'utf8');
  console.log(`Sitemap written to: ${publicPath}`);

  // Write to dist directory (for deployment)
  const distDir = path.resolve(__dirname, '../dist');
  if (fs.existsSync(distDir)) {
    const distPath = path.join(distDir, 'sitemap.xml');
    fs.writeFileSync(distPath, xml, 'utf8');
    console.log(`Sitemap written to: ${distPath}`);
  }

  // Copy index.html to route directories for GitHub Pages SPA support
  copyIndexForSPA();
}

main();